<?php
// api/ai_preference_chat.php
// Gemini-first chat assistant for a selected traveller preference. This endpoint only
// advises; it does not create or update itinerary records.
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

require_once __DIR__ . "/../config/db_connect.php";
require_once __DIR__ . "/../config/api_keys.php";

header("Content-Type: application/json; charset=utf-8");

if (!isset($_SESSION["logged_in"]) || $_SESSION["logged_in"] !== true || ($_SESSION["role"] ?? "") !== "traveller") {
    http_response_code(401);
    respond_error("Unauthorized.");
}

$travellerId = (int)($_SESSION["traveller_id"] ?? 0);
$preferenceId = (int)($_POST["preference_id"] ?? 0);
$message = sanitize_text((string)($_POST["message"] ?? ""), 450);

if ($travellerId <= 0) {
    http_response_code(401);
    respond_error("Unauthorized.");
}
if ($preferenceId <= 0) {
    http_response_code(422);
    respond_error("Please select a saved preference first.");
}
if ($message === "") {
    http_response_code(422);
    respond_error("Please type a question for the AI assistant.");
}

$preference = load_preference($conn, $travellerId, $preferenceId);
if (!$preference) {
    http_response_code(404);
    respond_error("Selected preference was not found.");
}

$detectedDate = parse_trip_date($message);
if ($detectedDate && is_trip_date_intent_message($message)) {
    $originName = extract_origin_name($message);
    $draft = merge_ai_draft($travellerId, $preferenceId, [
        "start_date" => $detectedDate,
        "origin_name" => $originName,
        "requirements" => extract_requirement_notes($message),
    ]);
    $pendingActions = [[
        "type" => "fill_start_date",
        "start_date" => $detectedDate,
        "label" => format_display_date($detectedDate),
        "summary" => "Fill Start Date with " . format_display_date($detectedDate),
    ]];
    if ($originName !== "") {
        $pendingActions[] = [
            "type" => "fill_origin",
            "origin_name" => $originName,
            "label" => $originName,
            "summary" => "Use " . $originName . " as Starting Location",
        ];
    }
    echo json_encode([
        "status" => "success",
        "source" => "rule_based",
        "reply" => "I detected your intended trip start date as " . format_display_date($detectedDate) . ". Click Confirm Date if this is correct. I will only fill the Start Date field; the official itinerary will still be generated by the rule-based generator after you click Generate Itinerary." . ($originName !== "" ? "\n\nI also detected your starting location as " . $originName . ". Confirm it after the date so the route can start from the correct place." : ""),
        "ai_draft" => $draft,
        "pending_action" => $pendingActions[0],
        "pending_actions" => $pendingActions,
    ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

$result = call_ai_chat(build_chat_prompt($preference, $message));
if (($result["status"] ?? "") !== "success") {
    http_response_code(503);
    echo json_encode($result, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

$reply = clean_ai_reply((string)($result["content"] ?? ""));
$extracted = extract_planning_context($message, $reply);
$draft = merge_ai_draft($travellerId, $preferenceId, $extracted);
$pendingAction = null;
$pendingActions = [];
if (!empty($extracted["start_date"])) {
    $dateLabel = format_display_date((string)$extracted["start_date"]);
    $pendingActions[] = [
        "type" => "fill_start_date",
        "start_date" => (string)$extracted["start_date"],
        "label" => $dateLabel,
        "summary" => "Fill Start Date with " . $dateLabel,
    ];
    $reply .= "\n\nI also detected your intended trip start date as " . $dateLabel . ". Click Confirm Date if this is correct.";
}
if (!empty($extracted["origin_name"])) {
    $originName = (string)$extracted["origin_name"];
    $pendingActions[] = [
        "type" => "fill_origin",
        "origin_name" => $originName,
        "label" => $originName,
        "summary" => "Use " . $originName . " as Starting Location",
    ];
    $reply .= "\n\nI also detected your starting location as " . $originName . ". Click Confirm Location if this is correct.";
}
$pendingAction = $pendingActions[0] ?? null;

echo json_encode([
    "status" => "success",
    "source" => (string)($result["source"] ?? "ai"),
    "model" => (string)($result["model"] ?? ""),
    "reply" => $reply,
    "ai_draft" => $draft,
    "pending_action" => $pendingAction,
    "pending_actions" => $pendingActions,
], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
exit;

function load_preference(mysqli $conn, int $travellerId, int $preferenceId): ?array
{
    $stmt = $conn->prepare("
        SELECT preference_id, trip_days, budget, budget_tier, transport_type,
               traveller_type, travel_pace, dietary_preference, preferred_visit_time,
               accessibility_needs, interests, preferred_states, preferred_districts
        FROM traveller_preferences
        WHERE preference_id = ? AND traveller_id = ?
        LIMIT 1
    ");
    if (!$stmt) return null;
    $stmt->bind_param("ii", $preferenceId, $travellerId);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $stmt->close();
    if (!$row) return null;

    $row["interests"] = preference_interest_csv($conn, $preferenceId, (string)($row["interests"] ?? ""));
    $row["preferred_states"] = preference_state_csv($conn, $preferenceId, (string)($row["preferred_states"] ?? ""));
    return $row;
}

function build_chat_prompt(array $pref, string $message): string
{
    $context = [
        "days" => (int)$pref["trip_days"],
        "budget_rm" => (float)$pref["budget"],
        "budget_tier" => sanitize_text((string)($pref["budget_tier"] ?? "normal"), 40),
        "transport" => sanitize_text((string)($pref["transport_type"] ?? "car"), 40),
        "traveller" => sanitize_text((string)($pref["traveller_type"] ?? "solo"), 40),
        "pace" => sanitize_text((string)($pref["travel_pace"] ?? "normal"), 40),
        "diet" => sanitize_text((string)($pref["dietary_preference"] ?? "none"), 50),
        "visit_time" => sanitize_text((string)($pref["preferred_visit_time"] ?? "any"), 50),
        "accessibility" => sanitize_text((string)($pref["accessibility_needs"] ?? ""), 120),
        "interests" => sanitize_text((string)($pref["interests"] ?? ""), 160),
        "states" => sanitize_text((string)($pref["preferred_states"] ?? ""), 120),
        "districts" => sanitize_text((string)($pref["preferred_districts"] ?? ""), 120),
    ];

    return "Task: Answer the traveller briefly before itinerary generation.\n"
        . "Rules: Do not create a fake itinerary. Do not claim anything is saved. If the user provides a date, origin, hotel need, accessibility need, or other requirement, say it needs confirmation before use. Reply under 90 words. Plain text only.\n"
        . "Preference JSON:\n"
        . json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)
        . "\nTraveller question:\n"
        . sanitize_text($message, 450);
}

function call_ai_chat(string $prompt): array
{
    $gemini = call_gemini_chat($prompt);
    if (($gemini["status"] ?? "") === "success") {
        return $gemini;
    }
    if (($gemini["message"] ?? "") !== "") {
        error_log("Gemini preference chat fallback to Ollama: " . $gemini["message"]);
    }

    $model = defined("OLLAMA_MODEL") ? trim((string)OLLAMA_MODEL) : "qwen2.5:3b";
    if ($model === "") $model = "qwen2.5:3b";
    return call_ollama_chat($model, $prompt);
}

function call_gemini_chat(string $prompt): array
{
    $apiKey = defined("GEMINI_API_KEY") ? trim((string)GEMINI_API_KEY) : "";
    if ($apiKey === "") {
        return ["status" => "skipped", "message" => "Gemini API key is not configured.", "source" => "gemini"];
    }
    if (!function_exists("curl_init")) {
        return ["status" => "error", "message" => "PHP cURL is not enabled.", "source" => "gemini"];
    }

    $model = defined("GEMINI_MODEL") && trim((string)GEMINI_MODEL) !== ""
        ? trim((string)GEMINI_MODEL)
        : "gemini-2.5-flash";
    $model = preg_replace("#^models/#", "", $model) ?? $model;
    $url = "https://generativelanguage.googleapis.com/v1beta/models/" . rawurlencode($model) . ":generateContent";

    $payload = [
        "systemInstruction" => [
            "parts" => [[
                "text" => "You are a controlled preference assistant before itinerary generation. Understand the traveller's natural message, but do not create or save a formal itinerary. If the user provides date, origin, hotel need, accessibility need, or trip requirement, explain it needs confirmation. Keep replies short, practical, same language when possible, plain text only.",
            ]],
        ],
        "contents" => [[
            "role" => "user",
            "parts" => [["text" => $prompt]],
        ]],
        "generationConfig" => [
            "temperature" => 0.25,
            "maxOutputTokens" => 180,
        ],
    ];

    $payloadJson = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    if ($payloadJson === false) {
        return ["status" => "error", "message" => "Gemini request could not be prepared.", "source" => "gemini"];
    }

    $start = microtime(true);
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_HTTPHEADER => [
            "Content-Type: application/json",
            "x-goog-api-key: " . $apiKey,
        ],
        CURLOPT_POSTFIELDS => $payloadJson,
        CURLOPT_TIMEOUT => 35,
        CURLOPT_CONNECTTIMEOUT => 8,
        CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
    ]);

    $raw = curl_exec($ch);
    $err = curl_error($ch);
    $code = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    $duration = round(microtime(true) - $start, 2);
    error_log("Gemini preference chat duration: " . $duration . "s | HTTP " . $code . " | Model: " . $model);

    if ($raw === false || $err !== "") {
        return ["status" => "error", "message" => "Gemini request failed: " . $err, "source" => "gemini"];
    }

    $json = json_decode($raw, true);
    if ($code < 200 || $code >= 300 || !is_array($json)) {
        $message = is_array($json) ? (string)($json["error"]["message"] ?? "Gemini HTTP error " . $code) : "Gemini HTTP error " . $code;
        return ["status" => "error", "message" => $message, "source" => "gemini"];
    }

    $text = "";
    foreach (($json["candidates"][0]["content"]["parts"] ?? []) as $part) {
        $text .= (string)($part["text"] ?? "");
    }
    $text = clean_ai_reply($text);
    if ($text === "") {
        return ["status" => "error", "message" => "Gemini returned an empty response.", "source" => "gemini"];
    }

    return ["status" => "success", "content" => $text, "source" => "gemini", "model" => $model];
}

function call_ollama_chat(string $model, string $prompt): array
{
    if (!function_exists("curl_init")) {
        return ["status" => "error", "message" => "PHP cURL is not enabled."];
    }

    $baseUrl = defined("OLLAMA_BASE_URL") ? trim((string)OLLAMA_BASE_URL) : "http://127.0.0.1:11434";
    $baseUrl = rtrim($baseUrl, "/");
    $url = str_ends_with($baseUrl, "/api") ? $baseUrl . "/chat" : $baseUrl . "/api/chat";

    $payload = [
        "model" => $model,
        "messages" => [
            [
                "role" => "system",
                "content" => "You are a controlled preference assistant before itinerary generation. Keep replies short, practical, and plain text only.",
            ],
            [
                "role" => "user",
                "content" => $prompt,
            ],
        ],
        "stream" => false,
        "options" => [
            "temperature" => 0.45,
            "num_ctx" => defined("OLLAMA_NUM_CTX") ? OLLAMA_NUM_CTX : 512,
            "num_predict" => 140,
        ],
    ];

    $payloadJson = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    if ($payloadJson === false) {
        return ["status" => "error", "message" => "AI request could not be prepared.", "source" => "ollama"];
    }

    error_log("Ollama preference chat payload size: " . strlen($payloadJson) . " bytes");
    $start = microtime(true);

    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_HTTPHEADER => ["Content-Type: application/json"],
        CURLOPT_POSTFIELDS => $payloadJson,
        CURLOPT_TIMEOUT => 60,
        CURLOPT_CONNECTTIMEOUT => 5,
        CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
    ]);

    $raw = curl_exec($ch);
    $err = curl_error($ch);
    $code = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    $duration = round(microtime(true) - $start, 2);
    error_log("Ollama preference chat duration: " . $duration . "s | HTTP " . $code . " | URL: " . $url);

    if ($raw === false || $err !== "") {
        error_log("Ollama preference chat request failed: " . $err . " | URL: " . $url);
        return ["status" => "error", "message" => "AI service is currently unavailable.", "source" => "ollama"];
    }

    $json = json_decode($raw, true);
    if ($code === 404 || (is_array($json) && isset($json["error"]) && stripos((string)$json["error"], "not found") !== false)) {
        return ["status" => "error", "message" => "AI model is not installed. Please run: ollama pull " . $model, "source" => "ollama"];
    }
    if ($code < 200 || $code >= 300 || !is_array($json) || !isset($json["message"]["content"])) {
        return ["status" => "error", "message" => "AI response is invalid. Please try again.", "source" => "ollama"];
    }

    return ["status" => "success", "content" => (string)$json["message"]["content"], "source" => "ollama", "model" => $model];
}

function preference_interest_csv(mysqli $conn, int $preferenceId, string $fallbackCsv): string
{
    $values = [];
    if (table_exists($conn, "traveller_preference_interests") && table_exists($conn, "travel_interests")) {
        $stmt = $conn->prepare("
            SELECT ti.interest_code
            FROM traveller_preference_interests tpi
            JOIN travel_interests ti ON ti.interest_id = tpi.interest_id
            WHERE tpi.preference_id = ?
            ORDER BY ti.interest_code
        ");
        if ($stmt) {
            $stmt->bind_param("i", $preferenceId);
            $stmt->execute();
            $res = $stmt->get_result();
            while ($row = $res->fetch_assoc()) $values[] = (string)$row["interest_code"];
            $stmt->close();
        }
    }
    return empty($values) ? trim($fallbackCsv) : implode(",", array_values(array_unique($values)));
}

function preference_state_csv(mysqli $conn, int $preferenceId, string $fallbackCsv): string
{
    $values = [];
    if (table_exists($conn, "traveller_preference_states") && table_exists($conn, "malaysia_states")) {
        $stmt = $conn->prepare("
            SELECT ms.state_name
            FROM traveller_preference_states tps
            JOIN malaysia_states ms ON ms.state_id = tps.state_id
            WHERE tps.preference_id = ?
            ORDER BY ms.state_name
        ");
        if ($stmt) {
            $stmt->bind_param("i", $preferenceId);
            $stmt->execute();
            $res = $stmt->get_result();
            while ($row = $res->fetch_assoc()) $values[] = (string)$row["state_name"];
            $stmt->close();
        }
    }
    return empty($values) ? trim($fallbackCsv) : implode(",", array_values(array_unique($values)));
}

function table_exists(mysqli $conn, string $table): bool
{
    $table = $conn->real_escape_string($table);
    $res = $conn->query("SHOW TABLES LIKE '$table'");
    return ($res && $res->num_rows > 0);
}

function sanitize_text(string $value, int $maxLen): string
{
    $value = trim(strip_tags($value));
    $value = preg_replace('/\s+/', ' ', $value) ?? "";
    if (function_exists("mb_substr")) return mb_substr($value, 0, $maxLen);
    return substr($value, 0, $maxLen);
}

function parse_trip_date(string $text): ?string
{
    $text = trim($text);
    $months = [
        "jan" => 1, "january" => 1,
        "feb" => 2, "february" => 2,
        "mar" => 3, "march" => 3,
        "apr" => 4, "april" => 4,
        "may" => 5,
        "jun" => 6, "june" => 6,
        "jul" => 7, "july" => 7,
        "aug" => 8, "august" => 8,
        "sep" => 9, "sept" => 9, "september" => 9,
        "oct" => 10, "october" => 10,
        "nov" => 11, "november" => 11,
        "dec" => 12, "december" => 12
    ];
    if (preg_match('/\b(\d{4})-(\d{1,2})-(\d{1,2})\b/', $text, $m)) {
        return valid_date((int)$m[1], (int)$m[2], (int)$m[3]);
    }
    if (preg_match('/\b(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})\b/', $text, $m)) {
        return valid_date((int)$m[3], (int)$m[2], (int)$m[1]);
    }
    if (preg_match('/\b(\d{1,2})(?:st|nd|rd|th)?[\s\/\-]+([a-zA-Z]+)[,\s\/\-]+(\d{4})\b/', $text, $m)) {
        $monthKey = strtolower($m[2]);
        if (isset($months[$monthKey])) {
            return valid_date((int)$m[3], $months[$monthKey], (int)$m[1]);
        }
    }
    if (preg_match('/\b([a-zA-Z]+)[\s\/\-]+(\d{1,2})(?:st|nd|rd|th)?[,\s\/\-]+(\d{4})\b/', $text, $m)) {
        $monthKey = strtolower($m[1]);
        if (isset($months[$monthKey])) {
            return valid_date((int)$m[3], $months[$monthKey], (int)$m[2]);
        }
    }
    if (preg_match('/\b(\d{1,2})(\d{4})([a-zA-Z]+)\b/', $text, $m)) {
        $monthKey = strtolower($m[3]);
        if (isset($months[$monthKey])) {
            return valid_date((int)$m[2], $months[$monthKey], (int)$m[1]);
        }
    }
    if (preg_match('/\b([a-zA-Z]+)(\d{1,2})(\d{4})\b/', $text, $m)) {
        $monthKey = strtolower($m[1]);
        if (isset($months[$monthKey])) {
            return valid_date((int)$m[3], $months[$monthKey], (int)$m[2]);
        }
    }
    if (preg_match('/\b(\d{1,2})(?:st|nd|rd|th)?\s*([a-zA-Z]+)\s*(\d{4})\b/', $text, $m)) {
        $monthKey = strtolower($m[2]);
        if (isset($months[$monthKey])) {
            return valid_date((int)$m[3], $months[$monthKey], (int)$m[1]);
        }
    }
    if (preg_match('/\b([a-zA-Z]+)\s*(\d{1,2})(?:st|nd|rd|th)?[,]?\s*(\d{4})\b/', $text, $m)) {
        $monthKey = strtolower($m[1]);
        if (isset($months[$monthKey])) {
            return valid_date((int)$m[3], $months[$monthKey], (int)$m[2]);
        }
    }
    return null;
}

function valid_date(int $year, int $month, int $day): ?string
{
    if (!checkdate($month, $day, $year)) return null;
    return sprintf("%04d-%02d-%02d", $year, $month, $day);
}

function format_display_date(string $date): string
{
    $dt = DateTime::createFromFormat("Y-m-d", $date);
    return $dt ? $dt->format("d M Y") : $date;
}

function clean_ai_reply(string $text): string
{
    $text = preg_replace('/\*{1,3}([^*]+)\*{1,3}/u', '$1', $text) ?? $text;
    $text = preg_replace('/^\s{0,3}#{1,6}\s*/m', '', $text) ?? $text;
    $text = preg_replace('/\s+/', ' ', $text) ?? $text;
    return sanitize_text(trim($text), 900);
}

function is_trip_date_intent_message(string $message): bool
{
    return (bool)preg_match('/\b(start|date|trip|travel|go|going|visit|arrive|depart|leave|change|update|instead|actually|plan|planning)\b|no[, ]|not|wrong|\x{4E0D}\x{662F}|\x{6539}|\x{66F4}\x{6539}|\x{6362}|\x{53BB}|\x{51FA}\x{53D1}|\x{65E5}\x{671F}|\x{884C}\x{7A0B}|\x{65C5}\x{884C}|\x{73A9}|\x{5230}|\x{62B5}\x{8FBE}/iu', $message);
}

function extract_planning_context(string $message, string $reply): array
{
    $combined = trim($message . "\n" . $reply);
    $context = [
        "requirements" => extract_requirement_notes($message),
    ];
    $date = parse_trip_date($combined);
    if ($date && (is_trip_date_intent_message($message) || is_trip_date_intent_message($reply))) {
        $context["start_date"] = $date;
    }
    if (preg_match('/\b(hotel|accommodation|stay|room|nearby hotel|budget hotel|luxury hotel)\b|\x{9152}\x{5E97}|\x{4F4F}\x{5BBF}|\x{623F}\x{95F4}/iu', $message)) {
        $context["hotel_requirement"] = sanitize_text($message, 180);
    }
    $originName = extract_origin_name($message);
    if ($originName !== "") {
        $context["origin_name"] = $originName;
    }
    return $context;
}

function extract_origin_name(string $message): string
{
    $patterns = [
        '/\b(?:start(?:ing)? from|depart(?:ing)? from|leave from|leaving from|from)\s+(.+?)(?:\s+(?:to|on|at|for)\b|[.!?]|$)/iu',
        '/\b(?:my starting location is|starting location is|origin is)\s+(.+?)(?:[.!?]|$)/iu',
        '/(?:从|由|出发地是|起点是)\s*(.+?)(?:出发|去|到|，|。|,|$)/u',
    ];
    foreach ($patterns as $pattern) {
        if (preg_match($pattern, $message, $m)) {
            $value = sanitize_text((string)$m[1], 120);
            $value = preg_replace('/\b(?:on|at|for|to)\s*$/iu', '', $value) ?? $value;
            return trim($value);
        }
    }
    return "";
}

function extract_requirement_notes(string $message): array
{
    if (!preg_match('/\b(want|need|prefer|avoid|include|must|should|with|without|halal|vegetarian|elderly|wheelchair|kids|family|cheap|budget|luxury|near|nearby)\b|\x{8981}|\x{9700}\x{8981}|\x{504F}\x{597D}|\x{907F}\x{514D}|\x{5305}\x{62EC}|\x{6E05}\x{771F}|\x{8001}\x{4EBA}|\x{8F6E}\x{6905}|\x{5BB6}\x{5EAD}|\x{4FBF}\x{5B9C}|\x{9AD8}\x{7EA7}/iu', $message)) {
        return [];
    }
    return [sanitize_text($message, 180)];
}

function merge_ai_draft(int $travellerId, int $preferenceId, array $updates): array
{
    if (!isset($_SESSION["ai_preference_drafts"]) || !is_array($_SESSION["ai_preference_drafts"])) {
        $_SESSION["ai_preference_drafts"] = [];
    }
    if (!isset($_SESSION["ai_preference_drafts"][$travellerId]) || !is_array($_SESSION["ai_preference_drafts"][$travellerId])) {
        $_SESSION["ai_preference_drafts"][$travellerId] = [];
    }
    $draft = $_SESSION["ai_preference_drafts"][$travellerId][$preferenceId] ?? [
        "start_date" => "",
        "hotel_requirement" => "",
        "requirements" => [],
        "updated_at" => "",
    ];

    if (!empty($updates["start_date"])) $draft["start_date"] = (string)$updates["start_date"];
    if (!empty($updates["origin_name"])) $draft["origin_name"] = (string)$updates["origin_name"];
    if (!empty($updates["hotel_requirement"])) $draft["hotel_requirement"] = (string)$updates["hotel_requirement"];
    foreach (($updates["requirements"] ?? []) as $note) {
        $note = sanitize_text((string)$note, 180);
        if ($note !== "" && !in_array($note, $draft["requirements"], true)) {
            $draft["requirements"][] = $note;
        }
    }
    $draft["requirements"] = array_slice(array_values($draft["requirements"]), -5);
    $draft["updated_at"] = date("Y-m-d H:i:s");
    $_SESSION["ai_preference_drafts"][$travellerId][$preferenceId] = $draft;
    return format_ai_draft($draft);
}

function format_ai_draft(array $draft): array
{
    return [
        "start_date" => (string)($draft["start_date"] ?? ""),
        "start_date_label" => !empty($draft["start_date"]) ? format_display_date((string)$draft["start_date"]) : "",
        "origin_name" => (string)($draft["origin_name"] ?? ""),
        "hotel_requirement" => (string)($draft["hotel_requirement"] ?? ""),
        "requirements" => array_values($draft["requirements"] ?? []),
    ];
}

function respond_error(string $message): void
{
    echo json_encode(["status" => "error", "message" => $message], JSON_UNESCAPED_UNICODE);
    exit;
}
